
name: Publish Docker image to docker hub

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          docker build -t docker-sample .
          docker tag docker-sample:latest phani0707/pythonproject1:test1
          docker push phani0707/pythonproject1:test1
        

      
